// Datos ficticios pero realistas para la aplicación de gestión financiera

export interface Movimiento {
  id: string
  fecha: string
  tipo: "gasto" | "ingreso"
  categoria: string
  descripcion: string
  monto: number
  proyecto?: string
}

export interface DatosMensuales {
  mes: string
  mesCorto: string
  egresos: number
  ingresos: number
  administrativos: number
  proyectos: number
  otros: number
  movimientos: Movimiento[]
}

export interface DatosAnuales {
  [año: number]: DatosMensuales[]
}

// Datos de 2022
const datos2022: DatosMensuales[] = [
  {
    mes: "Enero",
    mesCorto: "Ene",
    egresos: 720500,
    ingresos: 380000,
    administrativos: -420000,
    proyectos: 180000,
    otros: -100500,
    movimientos: [
      {
        id: "1",
        fecha: "2022-01-05",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería El Constructor - Cemento y varillas",
        monto: 185000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "2",
        fecha: "2022-01-08",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Pago cuadrilla semana 1",
        monto: 280000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "3",
        fecha: "2022-01-12",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual - Avance obra",
        monto: 380000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "4",
        fecha: "2022-01-15",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos cuadrilla",
        monto: 45000,
      },
      {
        id: "5",
        fecha: "2022-01-20",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Combustible camión",
        monto: 68000,
      },
      {
        id: "6",
        fecha: "2022-01-25",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Pago contador",
        monto: 142500,
      },
    ],
  },
  {
    mes: "Febrero",
    mesCorto: "Feb",
    egresos: 890200,
    ingresos: 650000,
    administrativos: -380000,
    proyectos: 270000,
    otros: -130200,
    movimientos: [
      {
        id: "7",
        fecha: "2022-02-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería Construmax - Bloques",
        monto: 156000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "8",
        fecha: "2022-02-07",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual - Segundo desembolso",
        monto: 450000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "9",
        fecha: "2022-02-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Pago albañiles febrero",
        monto: 320000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "10",
        fecha: "2022-02-14",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación mezcladora",
        monto: 89000,
      },
      {
        id: "11",
        fecha: "2022-02-18",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Comisión supervisión obra externa",
        monto: 200000,
      },
      {
        id: "12",
        fecha: "2022-02-25",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos y refrigerios",
        monto: 52000,
      },
    ],
  },
  {
    mes: "Marzo",
    mesCorto: "Mar",
    egresos: 1250000,
    ingresos: 980000,
    administrativos: -450000,
    proyectos: 530000,
    otros: -270000,
    movimientos: [
      {
        id: "13",
        fecha: "2022-03-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Hierro y acero - Metalúrgica Nacional",
        monto: 420000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "14",
        fecha: "2022-03-05",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Anticipo proyecto nuevo",
        monto: 580000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "15",
        fecha: "2022-03-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Soldadores especializados",
        monto: 380000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "16",
        fecha: "2022-03-15",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual - Casa Rodríguez",
        monto: 400000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "17",
        fecha: "2022-03-20",
        tipo: "gasto",
        categoria: "Verjas",
        descripcion: "Instalación verjas perimetrales",
        monto: 185000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "18",
        fecha: "2022-03-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Permisos municipales",
        monto: 265000,
      },
    ],
  },
  {
    mes: "Abril",
    mesCorto: "Abr",
    egresos: 680000,
    ingresos: 520000,
    administrativos: -280000,
    proyectos: 240000,
    otros: -120000,
    movimientos: [
      {
        id: "19",
        fecha: "2022-04-04",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería Central - Tubería PVC",
        monto: 98000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "20",
        fecha: "2022-04-08",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Plomero instalación",
        monto: 145000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "21",
        fecha: "2022-04-12",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Pago parcial cliente",
        monto: 320000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "22",
        fecha: "2022-04-18",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos abril",
        monto: 38000,
      },
      {
        id: "23",
        fecha: "2022-04-22",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Asesoría técnica",
        monto: 200000,
      },
      {
        id: "24",
        fecha: "2022-04-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Flete materiales",
        monto: 75000,
      },
    ],
  },
  {
    mes: "Mayo",
    mesCorto: "May",
    egresos: 945000,
    ingresos: 780000,
    administrativos: -345000,
    proyectos: 435000,
    otros: -165000,
    movimientos: [
      {
        id: "25",
        fecha: "2022-05-03",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual - Avance mayo",
        monto: 480000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "26",
        fecha: "2022-05-08",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Electricidad - Cables y paneles",
        monto: 267000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "27",
        fecha: "2022-05-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Electricistas certificados",
        monto: 298000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "28",
        fecha: "2022-05-18",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Finiquito Casa Rodríguez",
        monto: 300000,
        proyecto: "Casa Rodríguez",
      },
      {
        id: "29",
        fecha: "2022-05-22",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Mantenimiento vehículo",
        monto: 125000,
      },
      {
        id: "30",
        fecha: "2022-05-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Seguros y pólizas",
        monto: 185000,
      },
    ],
  },
  {
    mes: "Junio",
    mesCorto: "Jun",
    egresos: 1120000,
    ingresos: 890000,
    administrativos: -420000,
    proyectos: 470000,
    otros: -230000,
    movimientos: [
      {
        id: "31",
        fecha: "2022-06-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Pintura y acabados",
        monto: 189000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "32",
        fecha: "2022-06-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual junio",
        monto: 520000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "33",
        fecha: "2022-06-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Pintores y acabadores",
        monto: 356000,
        proyecto: "Edificio Comercial",
      },
      {
        id: "34",
        fecha: "2022-06-15",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos equipo junio",
        monto: 67000,
      },
      {
        id: "35",
        fecha: "2022-06-20",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Consultoría proyecto externo",
        monto: 370000,
      },
      {
        id: "36",
        fecha: "2022-06-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Combustible y peajes",
        monto: 88000,
      },
    ],
  },
  {
    mes: "Julio",
    mesCorto: "Jul",
    egresos: 560000,
    ingresos: 420000,
    administrativos: -260000,
    proyectos: 160000,
    otros: -80000,
    movimientos: [
      {
        id: "37",
        fecha: "2022-07-05",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Pago contador trimestral",
        monto: 180000,
      },
      {
        id: "38",
        fecha: "2022-07-10",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Adelanto proyecto nuevo",
        monto: 420000,
        proyecto: "Remodelación Local",
      },
      {
        id: "39",
        fecha: "2022-07-15",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Materiales demolición",
        monto: 145000,
        proyecto: "Remodelación Local",
      },
      {
        id: "40",
        fecha: "2022-07-20",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Cuadrilla demolición",
        monto: 168000,
        proyecto: "Remodelación Local",
      },
      {
        id: "41",
        fecha: "2022-07-25",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Refrigerios julio",
        monto: 42000,
      },
    ],
  },
  {
    mes: "Agosto",
    mesCorto: "Ago",
    egresos: 785000,
    ingresos: 620000,
    administrativos: -285000,
    proyectos: 335000,
    otros: -115000,
    movimientos: [
      {
        id: "42",
        fecha: "2022-08-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería - Cielo raso",
        monto: 198000,
        proyecto: "Remodelación Local",
      },
      {
        id: "43",
        fecha: "2022-08-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Segundo pago remodelación",
        monto: 380000,
        proyecto: "Remodelación Local",
      },
      {
        id: "44",
        fecha: "2022-08-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Instaladores agosto",
        monto: 245000,
        proyecto: "Remodelación Local",
      },
      {
        id: "45",
        fecha: "2022-08-18",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Comisión referido",
        monto: 240000,
      },
      {
        id: "46",
        fecha: "2022-08-22",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación compresor",
        monto: 156000,
      },
      {
        id: "47",
        fecha: "2022-08-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Alquiler grúa",
        monto: 89000,
      },
    ],
  },
  {
    mes: "Septiembre",
    mesCorto: "Sep",
    egresos: 920000,
    ingresos: 750000,
    administrativos: -320000,
    proyectos: 430000,
    otros: -170000,
    movimientos: [
      {
        id: "48",
        fecha: "2022-09-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Piso cerámico importado",
        monto: 312000,
        proyecto: "Remodelación Local",
      },
      {
        id: "49",
        fecha: "2022-09-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Tercer desembolso",
        monto: 450000,
        proyecto: "Remodelación Local",
      },
      {
        id: "50",
        fecha: "2022-09-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Colocadores de piso",
        monto: 278000,
        proyecto: "Remodelación Local",
      },
      {
        id: "51",
        fecha: "2022-09-15",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos septiembre",
        monto: 58000,
      },
      {
        id: "52",
        fecha: "2022-09-20",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Nuevo proyecto aprobado",
        monto: 300000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "53",
        fecha: "2022-09-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Licencias y permisos",
        monto: 195000,
      },
    ],
  },
  {
    mes: "Octubre",
    mesCorto: "Oct",
    egresos: 1080000,
    ingresos: 920000,
    administrativos: -380000,
    proyectos: 540000,
    otros: -160000,
    movimientos: [
      {
        id: "54",
        fecha: "2022-10-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Concreto premezclado",
        monto: 425000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "55",
        fecha: "2022-10-07",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual octubre",
        monto: 620000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "56",
        fecha: "2022-10-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Cuadrilla fundaciones",
        monto: 345000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "57",
        fecha: "2022-10-18",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Finiquito Remodelación",
        monto: 300000,
        proyecto: "Remodelación Local",
      },
      {
        id: "58",
        fecha: "2022-10-22",
        tipo: "gasto",
        categoria: "Verjas",
        descripcion: "Portones metálicos",
        monto: 167000,
        proyecto: "Remodelación Local",
      },
      {
        id: "59",
        fecha: "2022-10-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Fletes octubre",
        monto: 78000,
      },
    ],
  },
  {
    mes: "Noviembre",
    mesCorto: "Nov",
    egresos: 1340000,
    ingresos: 1100000,
    administrativos: -440000,
    proyectos: 660000,
    otros: -200000,
    movimientos: [
      {
        id: "60",
        fecha: "2022-11-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Acero estructural",
        monto: 520000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "61",
        fecha: "2022-11-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Segundo desembolso Apts",
        monto: 780000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "62",
        fecha: "2022-11-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Armadores estructura",
        monto: 398000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "63",
        fecha: "2022-11-15",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos noviembre",
        monto: 72000,
      },
      {
        id: "64",
        fecha: "2022-11-20",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Bono fin de año cliente",
        monto: 320000,
      },
      {
        id: "65",
        fecha: "2022-11-28",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Service vehículos",
        monto: 145000,
      },
    ],
  },
  {
    mes: "Diciembre",
    mesCorto: "Dic",
    egresos: 680000,
    ingresos: 890000,
    administrativos: -280000,
    proyectos: 490000,
    otros: -90000,
    movimientos: [
      {
        id: "66",
        fecha: "2022-12-05",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Aguinaldos personal",
        monto: 480000,
      },
      {
        id: "67",
        fecha: "2022-12-10",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual diciembre",
        monto: 590000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "68",
        fecha: "2022-12-15",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Cena navideña equipo",
        monto: 125000,
      },
      {
        id: "69",
        fecha: "2022-12-18",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Bono navideño cliente",
        monto: 300000,
      },
      {
        id: "70",
        fecha: "2022-12-22",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Materiales reserva 2023",
        monto: 175000,
      },
    ],
  },
]

// Datos de 2023
const datos2023: DatosMensuales[] = [
  {
    mes: "Enero",
    mesCorto: "Ene",
    egresos: 856000,
    ingresos: 620000,
    administrativos: -356000,
    proyectos: 264000,
    otros: -136000,
    movimientos: [
      {
        id: "101",
        fecha: "2023-01-04",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería El Maestro - Inicio año",
        monto: 245000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "102",
        fecha: "2023-01-09",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Reinicio cuadrilla enero",
        monto: 312000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "103",
        fecha: "2023-01-12",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual - Primer pago 2023",
        monto: 420000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "104",
        fecha: "2023-01-18",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos primera quincena",
        monto: 52000,
      },
      {
        id: "105",
        fecha: "2023-01-22",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Consultoría inicio año",
        monto: 200000,
      },
      {
        id: "106",
        fecha: "2023-01-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Renovación permisos",
        monto: 178000,
      },
    ],
  },
  {
    mes: "Febrero",
    mesCorto: "Feb",
    egresos: 1120000,
    ingresos: 850000,
    administrativos: -420000,
    proyectos: 430000,
    otros: -190000,
    movimientos: [
      {
        id: "107",
        fecha: "2023-02-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ventanería aluminio",
        monto: 385000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "108",
        fecha: "2023-02-07",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cuarto desembolso Apts",
        monto: 580000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "109",
        fecha: "2023-02-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Instaladores ventanas",
        monto: 268000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "110",
        fecha: "2023-02-15",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación montacargas",
        monto: 198000,
      },
      {
        id: "111",
        fecha: "2023-02-20",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Nuevo cliente - Bodega",
        monto: 270000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "112",
        fecha: "2023-02-26",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Fletes materiales",
        monto: 95000,
      },
    ],
  },
  {
    mes: "Marzo",
    mesCorto: "Mar",
    egresos: 1450000,
    ingresos: 1180000,
    administrativos: -550000,
    proyectos: 630000,
    otros: -270000,
    movimientos: [
      {
        id: "113",
        fecha: "2023-03-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Estructura metálica bodega",
        monto: 620000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "114",
        fecha: "2023-03-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Segundo pago bodega",
        monto: 750000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "115",
        fecha: "2023-03-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Soldadores certificados",
        monto: 425000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "116",
        fecha: "2023-03-16",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Avance Apartamentos",
        monto: 430000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "117",
        fecha: "2023-03-22",
        tipo: "gasto",
        categoria: "Verjas",
        descripcion: "Malla perimetral bodega",
        monto: 215000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "118",
        fecha: "2023-03-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Seguros construcción",
        monto: 290000,
      },
    ],
  },
  {
    mes: "Abril",
    mesCorto: "Abr",
    egresos: 980000,
    ingresos: 720000,
    administrativos: -380000,
    proyectos: 340000,
    otros: -140000,
    movimientos: [
      {
        id: "119",
        fecha: "2023-04-04",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Láminas techo bodega",
        monto: 345000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "120",
        fecha: "2023-04-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Tercer pago bodega",
        monto: 480000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "121",
        fecha: "2023-04-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Techadores abril",
        monto: 285000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "122",
        fecha: "2023-04-18",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos cuadrilla",
        monto: 68000,
      },
      {
        id: "123",
        fecha: "2023-04-22",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Referencia cliente nuevo",
        monto: 240000,
      },
      {
        id: "124",
        fecha: "2023-04-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Combustible abril",
        monto: 82000,
      },
    ],
  },
  {
    mes: "Mayo",
    mesCorto: "May",
    egresos: 1280000,
    ingresos: 1050000,
    administrativos: -480000,
    proyectos: 570000,
    otros: -230000,
    movimientos: [
      {
        id: "125",
        fecha: "2023-05-02",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Pago final bodega",
        monto: 680000,
        proyecto: "Bodega Industrial",
      },
      {
        id: "126",
        fecha: "2023-05-06",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Acabados Apartamentos",
        monto: 425000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "127",
        fecha: "2023-05-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Acabadores mayo",
        monto: 365000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "128",
        fecha: "2023-05-15",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Nuevo proyecto residencial",
        monto: 370000,
        proyecto: "Casa Morales",
      },
      {
        id: "129",
        fecha: "2023-05-22",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación excavadora",
        monto: 245000,
      },
      {
        id: "130",
        fecha: "2023-05-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Contabilidad trimestre",
        monto: 198000,
      },
    ],
  },
  {
    mes: "Junio",
    mesCorto: "Jun",
    egresos: 890000,
    ingresos: 680000,
    administrativos: -290000,
    proyectos: 390000,
    otros: -120000,
    movimientos: [
      {
        id: "131",
        fecha: "2023-06-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Bloques y cemento",
        monto: 278000,
        proyecto: "Casa Morales",
      },
      {
        id: "132",
        fecha: "2023-06-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Segundo pago Casa Morales",
        monto: 420000,
        proyecto: "Casa Morales",
      },
      {
        id: "133",
        fecha: "2023-06-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Albañilería junio",
        monto: 312000,
        proyecto: "Casa Morales",
      },
      {
        id: "134",
        fecha: "2023-06-18",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos junio",
        monto: 58000,
      },
      {
        id: "135",
        fecha: "2023-06-22",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Asesoría técnica",
        monto: 260000,
      },
      {
        id: "136",
        fecha: "2023-06-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Fletes y combustible",
        monto: 92000,
      },
    ],
  },
  {
    mes: "Julio",
    mesCorto: "Jul",
    egresos: 1150000,
    ingresos: 980000,
    administrativos: -450000,
    proyectos: 530000,
    otros: -170000,
    movimientos: [
      {
        id: "137",
        fecha: "2023-07-04",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Avance final Apartamentos",
        monto: 620000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "138",
        fecha: "2023-07-08",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Pisos y cerámicas",
        monto: 385000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "139",
        fecha: "2023-07-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Instaladores julio",
        monto: 342000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "140",
        fecha: "2023-07-18",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Tercer pago Casa Morales",
        monto: 360000,
        proyecto: "Casa Morales",
      },
      {
        id: "141",
        fecha: "2023-07-22",
        tipo: "gasto",
        categoria: "Verjas",
        descripcion: "Barandas escalera",
        monto: 178000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "142",
        fecha: "2023-07-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Inspecciones municipales",
        monto: 145000,
      },
    ],
  },
  {
    mes: "Agosto",
    mesCorto: "Ago",
    egresos: 1380000,
    ingresos: 1150000,
    administrativos: -480000,
    proyectos: 670000,
    otros: -230000,
    movimientos: [
      {
        id: "143",
        fecha: "2023-08-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Sistema eléctrico completo",
        monto: 485000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "144",
        fecha: "2023-08-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Penúltimo pago Apts",
        monto: 720000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "145",
        fecha: "2023-08-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Electricistas certificados",
        monto: 398000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "146",
        fecha: "2023-08-15",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos agosto",
        monto: 72000,
      },
      {
        id: "147",
        fecha: "2023-08-20",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Proyecto express",
        monto: 430000,
        proyecto: "Reparación Comercial",
      },
      {
        id: "148",
        fecha: "2023-08-28",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Mantenimiento preventivo",
        monto: 168000,
      },
    ],
  },
  {
    mes: "Septiembre",
    mesCorto: "Sep",
    egresos: 920000,
    ingresos: 780000,
    administrativos: -320000,
    proyectos: 460000,
    otros: -140000,
    movimientos: [
      {
        id: "149",
        fecha: "2023-09-04",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Pintura y acabados finales",
        monto: 268000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "150",
        fecha: "2023-09-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Finiquito Apartamentos Norte",
        monto: 520000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "151",
        fecha: "2023-09-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Pintores septiembre",
        monto: 285000,
        proyecto: "Apartamentos Norte",
      },
      {
        id: "152",
        fecha: "2023-09-16",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Bono entrega exitosa",
        monto: 260000,
      },
      {
        id: "153",
        fecha: "2023-09-22",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Mudanza equipos",
        monto: 125000,
      },
      {
        id: "154",
        fecha: "2023-09-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Cierre contable trimestre",
        monto: 178000,
      },
    ],
  },
  {
    mes: "Octubre",
    mesCorto: "Oct",
    egresos: 1050000,
    ingresos: 820000,
    administrativos: -350000,
    proyectos: 470000,
    otros: -180000,
    movimientos: [
      {
        id: "155",
        fecha: "2023-10-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Materiales techo Casa Morales",
        monto: 325000,
        proyecto: "Casa Morales",
      },
      {
        id: "156",
        fecha: "2023-10-07",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cuarto pago Casa Morales",
        monto: 480000,
        proyecto: "Casa Morales",
      },
      {
        id: "157",
        fecha: "2023-10-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Techadores octubre",
        monto: 298000,
        proyecto: "Casa Morales",
      },
      {
        id: "158",
        fecha: "2023-10-16",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Anticipo proyecto nuevo",
        monto: 340000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "159",
        fecha: "2023-10-22",
        tipo: "gasto",
        categoria: "Verjas",
        descripcion: "Portón eléctrico",
        monto: 245000,
        proyecto: "Casa Morales",
      },
      {
        id: "160",
        fecha: "2023-10-28",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos octubre",
        monto: 62000,
      },
    ],
  },
  {
    mes: "Noviembre",
    mesCorto: "Nov",
    egresos: 1420000,
    ingresos: 1280000,
    administrativos: -520000,
    proyectos: 760000,
    otros: -260000,
    movimientos: [
      {
        id: "161",
        fecha: "2023-11-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Demolición y preparación",
        monto: 445000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "162",
        fecha: "2023-11-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Segundo pago Oficinas",
        monto: 680000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "163",
        fecha: "2023-11-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Cuadrilla demolición",
        monto: 368000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "164",
        fecha: "2023-11-15",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Finiquito Casa Morales",
        monto: 600000,
        proyecto: "Casa Morales",
      },
      {
        id: "165",
        fecha: "2023-11-22",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación mezcladora",
        monto: 198000,
      },
      {
        id: "166",
        fecha: "2023-11-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Retiro escombros",
        monto: 145000,
      },
    ],
  },
  {
    mes: "Diciembre",
    mesCorto: "Dic",
    egresos: 780000,
    ingresos: 1050000,
    administrativos: -380000,
    proyectos: 550000,
    otros: -70000,
    movimientos: [
      {
        id: "167",
        fecha: "2023-12-04",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Aguinaldos empleados",
        monto: 520000,
      },
      {
        id: "168",
        fecha: "2023-12-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Tercer pago Oficinas",
        monto: 580000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "169",
        fecha: "2023-12-12",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Reserva materiales 2024",
        monto: 185000,
      },
      {
        id: "170",
        fecha: "2023-12-15",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Bono fin de año",
        monto: 470000,
      },
      {
        id: "171",
        fecha: "2023-12-20",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Celebración navideña",
        monto: 145000,
      },
    ],
  },
]

// Datos de 2024
const datos2024: DatosMensuales[] = [
  {
    mes: "Enero",
    mesCorto: "Ene",
    egresos: 945000,
    ingresos: 720000,
    administrativos: -345000,
    proyectos: 375000,
    otros: -145000,
    movimientos: [
      {
        id: "201",
        fecha: "2024-01-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería Nacional - Inicio 2024",
        monto: 298000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "202",
        fecha: "2024-01-08",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Albañiles enero",
        monto: 325000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "203",
        fecha: "2024-01-12",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual enero",
        monto: 520000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "204",
        fecha: "2024-01-18",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos cuadrilla",
        monto: 58000,
      },
      {
        id: "205",
        fecha: "2024-01-22",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Asesoría proyecto externo",
        monto: 200000,
      },
      {
        id: "206",
        fecha: "2024-01-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Renovación licencias",
        monto: 185000,
      },
    ],
  },
  {
    mes: "Febrero",
    mesCorto: "Feb",
    egresos: 1180000,
    ingresos: 920000,
    administrativos: -480000,
    proyectos: 440000,
    otros: -220000,
    movimientos: [
      {
        id: "207",
        fecha: "2024-02-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Sistema A/C comercial",
        monto: 425000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "208",
        fecha: "2024-02-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Quinto pago Oficinas",
        monto: 620000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "209",
        fecha: "2024-02-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Técnicos A/C",
        monto: 345000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "210",
        fecha: "2024-02-15",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación camión",
        monto: 178000,
      },
      {
        id: "211",
        fecha: "2024-02-20",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Nuevo proyecto pequeño",
        monto: 300000,
        proyecto: "Remodelación Apartamento",
      },
      {
        id: "212",
        fecha: "2024-02-26",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Combustible febrero",
        monto: 95000,
      },
    ],
  },
  {
    mes: "Marzo",
    mesCorto: "Mar",
    egresos: 1350000,
    ingresos: 1180000,
    administrativos: -550000,
    proyectos: 630000,
    otros: -280000,
    movimientos: [
      {
        id: "213",
        fecha: "2024-03-04",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Divisiones gypsum",
        monto: 385000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "214",
        fecha: "2024-03-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Sexto pago Oficinas",
        monto: 720000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "215",
        fecha: "2024-03-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Instaladores gypsum",
        monto: 398000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "216",
        fecha: "2024-03-16",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Pago Remodelación",
        monto: 460000,
        proyecto: "Remodelación Apartamento",
      },
      {
        id: "217",
        fecha: "2024-03-22",
        tipo: "gasto",
        categoria: "Verjas",
        descripcion: "División metálica",
        monto: 235000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "218",
        fecha: "2024-03-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Inspecciones CFIA",
        monto: 195000,
      },
    ],
  },
  {
    mes: "Abril",
    mesCorto: "Abr",
    egresos: 890000,
    ingresos: 680000,
    administrativos: -290000,
    proyectos: 390000,
    otros: -130000,
    movimientos: [
      {
        id: "219",
        fecha: "2024-04-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Pisos laminados",
        monto: 278000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "220",
        fecha: "2024-04-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Avance abril",
        monto: 480000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "221",
        fecha: "2024-04-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Instaladores piso",
        monto: 268000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "222",
        fecha: "2024-04-18",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos abril",
        monto: 62000,
      },
      {
        id: "223",
        fecha: "2024-04-22",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Referencia nuevo cliente",
        monto: 200000,
      },
      {
        id: "224",
        fecha: "2024-04-28",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Fletes materiales",
        monto: 78000,
      },
    ],
  },
  {
    mes: "Mayo",
    mesCorto: "May",
    egresos: 1150000,
    ingresos: 980000,
    administrativos: -450000,
    proyectos: 530000,
    otros: -170000,
    movimientos: [
      {
        id: "225",
        fecha: "2024-05-02",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Finiquito Oficinas Centro",
        monto: 680000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "226",
        fecha: "2024-05-06",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Pintura y acabados",
        monto: 312000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "227",
        fecha: "2024-05-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Pintores mayo",
        monto: 345000,
        proyecto: "Oficinas Centro",
      },
      {
        id: "228",
        fecha: "2024-05-15",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Nuevo proyecto comercial",
        monto: 300000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "229",
        fecha: "2024-05-22",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Service vehículos",
        monto: 198000,
      },
      {
        id: "230",
        fecha: "2024-05-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Contabilidad mayo",
        monto: 165000,
      },
    ],
  },
  {
    mes: "Junio",
    mesCorto: "Jun",
    egresos: 1280000,
    ingresos: 1050000,
    administrativos: -480000,
    proyectos: 570000,
    otros: -210000,
    movimientos: [
      {
        id: "231",
        fecha: "2024-06-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Estructura Local Sur",
        monto: 425000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "232",
        fecha: "2024-06-07",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Segundo pago Local",
        monto: 620000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "233",
        fecha: "2024-06-11",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Cuadrilla junio",
        monto: 385000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "234",
        fecha: "2024-06-16",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Proyecto express",
        monto: 430000,
        proyecto: "Reparación Techo",
      },
      {
        id: "235",
        fecha: "2024-06-22",
        tipo: "gasto",
        categoria: "Verjas",
        descripcion: "Cortinas metálicas",
        monto: 285000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "236",
        fecha: "2024-06-28",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos junio",
        monto: 72000,
      },
    ],
  },
  {
    mes: "Julio",
    mesCorto: "Jul",
    egresos: 980000,
    ingresos: 850000,
    administrativos: -380000,
    proyectos: 470000,
    otros: -130000,
    movimientos: [
      {
        id: "237",
        fecha: "2024-07-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Sistema eléctrico",
        monto: 345000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "238",
        fecha: "2024-07-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Tercer pago Local",
        monto: 520000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "239",
        fecha: "2024-07-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Electricistas julio",
        monto: 298000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "240",
        fecha: "2024-07-15",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Consultoría técnica",
        monto: 330000,
      },
      {
        id: "241",
        fecha: "2024-07-22",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Combustible julio",
        monto: 85000,
      },
      {
        id: "242",
        fecha: "2024-07-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Permisos municipales",
        monto: 145000,
      },
    ],
  },
  {
    mes: "Agosto",
    mesCorto: "Ago",
    egresos: 1120000,
    ingresos: 920000,
    administrativos: -420000,
    proyectos: 500000,
    otros: -180000,
    movimientos: [
      {
        id: "243",
        fecha: "2024-08-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Acabados Local Sur",
        monto: 365000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "244",
        fecha: "2024-08-06",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Finiquito Local Sur",
        monto: 620000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "245",
        fecha: "2024-08-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Acabadores agosto",
        monto: 325000,
        proyecto: "Local Comercial Sur",
      },
      {
        id: "246",
        fecha: "2024-08-15",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Nuevo proyecto vivienda",
        monto: 300000,
        proyecto: "Casa Hernández",
      },
      {
        id: "247",
        fecha: "2024-08-22",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación herramientas",
        monto: 168000,
      },
      {
        id: "248",
        fecha: "2024-08-28",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos agosto",
        monto: 68000,
      },
    ],
  },
  {
    mes: "Septiembre",
    mesCorto: "Sep",
    egresos: 1350000,
    ingresos: 1180000,
    administrativos: -550000,
    proyectos: 630000,
    otros: -250000,
    movimientos: [
      {
        id: "249",
        fecha: "2024-09-03",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Fundaciones Casa Hernández",
        monto: 485000,
        proyecto: "Casa Hernández",
      },
      {
        id: "250",
        fecha: "2024-09-07",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Segundo pago Hernández",
        monto: 680000,
        proyecto: "Casa Hernández",
      },
      {
        id: "251",
        fecha: "2024-09-11",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Cuadrilla fundaciones",
        monto: 398000,
        proyecto: "Casa Hernández",
      },
      {
        id: "252",
        fecha: "2024-09-16",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Proyecto remodelación",
        monto: 500000,
        proyecto: "Remodelación Consultorio",
      },
      {
        id: "253",
        fecha: "2024-09-22",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Alquiler maquinaria",
        monto: 245000,
      },
      {
        id: "254",
        fecha: "2024-09-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Seguros y pólizas",
        monto: 198000,
      },
    ],
  },
  {
    mes: "Octubre",
    mesCorto: "Oct",
    egresos: 900780,
    ingresos: 450970,
    administrativos: -560000,
    proyectos: 275000,
    otros: -15000,
    movimientos: [
      {
        id: "255",
        fecha: "2024-10-02",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería El Constructor - Bloques",
        monto: 245000,
        proyecto: "Casa Hernández",
      },
      {
        id: "256",
        fecha: "2024-10-05",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Albañiles semana 1",
        monto: 185000,
        proyecto: "Casa Hernández",
      },
      {
        id: "257",
        fecha: "2024-10-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual - Avance",
        monto: 280000,
        proyecto: "Casa Hernández",
      },
      {
        id: "258",
        fecha: "2024-10-12",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos cuadrilla",
        monto: 42000,
      },
      {
        id: "259",
        fecha: "2024-10-15",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Tubería y accesorios",
        monto: 98500,
        proyecto: "Casa Hernández",
      },
      {
        id: "260",
        fecha: "2024-10-18",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Comisión supervisión",
        monto: 170970,
      },
      {
        id: "261",
        fecha: "2024-10-22",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Plomero instalación",
        monto: 125000,
        proyecto: "Casa Hernández",
      },
      {
        id: "262",
        fecha: "2024-10-25",
        tipo: "gasto",
        categoria: "Transporte",
        descripcion: "Combustible y fletes",
        monto: 65000,
      },
      {
        id: "263",
        fecha: "2024-10-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Pago contador mensual",
        monto: 140280,
      },
    ],
  },
  {
    mes: "Noviembre",
    mesCorto: "Nov",
    egresos: 1250000,
    ingresos: 980000,
    administrativos: -450000,
    proyectos: 530000,
    otros: -200000,
    movimientos: [
      {
        id: "264",
        fecha: "2024-11-04",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Techo y estructura",
        monto: 425000,
        proyecto: "Casa Hernández",
      },
      {
        id: "265",
        fecha: "2024-11-08",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cuarto pago Hernández",
        monto: 580000,
        proyecto: "Casa Hernández",
      },
      {
        id: "266",
        fecha: "2024-11-12",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Techadores noviembre",
        monto: 345000,
        proyecto: "Casa Hernández",
      },
      {
        id: "267",
        fecha: "2024-11-16",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Avance Consultorio",
        monto: 400000,
        proyecto: "Remodelación Consultorio",
      },
      {
        id: "268",
        fecha: "2024-11-22",
        tipo: "gasto",
        categoria: "Mecánica",
        descripcion: "Reparación compresor",
        monto: 178000,
      },
      {
        id: "269",
        fecha: "2024-11-28",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos noviembre",
        monto: 72000,
      },
    ],
  },
  {
    mes: "Diciembre",
    mesCorto: "Dic",
    egresos: 850000,
    ingresos: 1120000,
    administrativos: -450000,
    proyectos: 580000,
    otros: -90000,
    movimientos: [
      {
        id: "270",
        fecha: "2024-12-03",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Aguinaldos personal",
        monto: 580000,
      },
      {
        id: "271",
        fecha: "2024-12-07",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Pago final Consultorio",
        monto: 620000,
        proyecto: "Remodelación Consultorio",
      },
      {
        id: "272",
        fecha: "2024-12-11",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Reserva materiales 2025",
        monto: 195000,
      },
      {
        id: "273",
        fecha: "2024-12-15",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Bono fin de año cliente",
        monto: 500000,
      },
      {
        id: "274",
        fecha: "2024-12-20",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Cena navideña equipo",
        monto: 135000,
      },
    ],
  },
]

// Datos de 2025 (solo hasta mes actual simulado)
const datos2025: DatosMensuales[] = [
  {
    mes: "Enero",
    mesCorto: "Ene",
    egresos: 1080000,
    ingresos: 820000,
    administrativos: -380000,
    proyectos: 440000,
    otros: -180000,
    movimientos: [
      {
        id: "301",
        fecha: "2025-01-06",
        tipo: "gasto",
        categoria: "Materiales",
        descripcion: "Ferretería Construmax - Inicio 2025",
        monto: 385000,
        proyecto: "Casa Hernández",
      },
      {
        id: "302",
        fecha: "2025-01-10",
        tipo: "gasto",
        categoria: "Mano de obra",
        descripcion: "Reinicio cuadrilla",
        monto: 345000,
        proyecto: "Casa Hernández",
      },
      {
        id: "303",
        fecha: "2025-01-14",
        tipo: "ingreso",
        categoria: "Cheque",
        descripcion: "Cheque Mutual enero",
        monto: 520000,
        proyecto: "Casa Hernández",
      },
      {
        id: "304",
        fecha: "2025-01-18",
        tipo: "gasto",
        categoria: "Alimentación",
        descripcion: "Almuerzos enero",
        monto: 58000,
      },
      {
        id: "305",
        fecha: "2025-01-22",
        tipo: "ingreso",
        categoria: "Comisión",
        descripcion: "Asesoría técnica",
        monto: 300000,
      },
      {
        id: "306",
        fecha: "2025-01-28",
        tipo: "gasto",
        categoria: "Administrativo",
        descripcion: "Renovación anual permisos",
        monto: 212000,
      },
    ],
  },
]

export const datosAnuales: DatosAnuales = {
  2022: datos2022,
  2023: datos2023,
  2024: datos2024,
  2025: datos2025,
}

export const añosDisponibles = [2022, 2023, 2024, 2025]

export function obtenerDatosMes(año: number, mesIndex: number): DatosMensuales | null {
  const datosAño = datosAnuales[año]
  if (!datosAño || mesIndex < 0 || mesIndex >= datosAño.length) {
    return null
  }
  return datosAño[mesIndex]
}

export function obtenerResumenAnual(año: number) {
  const datosAño = datosAnuales[año]
  if (!datosAño) return null

  return datosAño.reduce(
    (acc, mes) => ({
      totalEgresos: acc.totalEgresos + mes.egresos,
      totalIngresos: acc.totalIngresos + mes.ingresos,
      totalAdministrativos: acc.totalAdministrativos + mes.administrativos,
      totalProyectos: acc.totalProyectos + mes.proyectos,
      totalOtros: acc.totalOtros + mes.otros,
    }),
    {
      totalEgresos: 0,
      totalIngresos: 0,
      totalAdministrativos: 0,
      totalProyectos: 0,
      totalOtros: 0,
    },
  )
}

export function formatearMoneda(valor: number): string {
  const absValor = Math.abs(valor)
  return new Intl.NumberFormat("es-CR").format(absValor)
}
